steps:
  # Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - 'build' 
  - '--tag=gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}:$SHORT_SHA'
  - '--tag=gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}:$TAG_NAME'
  - '--tag=gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}:latest'
  - '--build-arg'
  - 'ver=$TAG_NAME'
  - '-f'
  - './go/k8s/${_DEPL_SERVICE}/${_DEPL_VERSION}/Dockerfile'
  - '.'

  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}']
  # Deploy container image to Cloud Run
substitutions:
  _DEPL_SERVICE: flutter-build
  _DEPL_VERSION: main
images:
 - 'gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}'