steps:
  # Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/${_DEPL_SERVICE}${_DEPL_VERSION}:$SHORT_SHA', '-f', './go/k8s/Dockerfile', '.']

  # Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}:$SHORT_SHA']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - '${_DEPL_SERVICE}-${_DEPL_VERSION}'
  - '--allow-unauthenticated'
  - '--image'
  - 'gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}:$SHORT_SHA'
  - '--region'
  - 'europe-north1'
  - '--platform'
  - 'managed'
substitutions:
  _DEPL_SERVICE: bitonpaper
  _DEPL_VERSION: dev
images:
 - 'gcr.io/$PROJECT_ID/${_DEPL_SERVICE}-${_DEPL_VERSION}:$SHORT_SHA'